name: FactionsUI
main: fu\Main
api: 3.0.0
version: 1.0.3
author:  bumbumkill ##Don't change author!
description: "FactionsUI plugin for PMMP"

permissions:
 factionui:
  default: false
  description: "All cmd"
  children:
   factionui.cmd.use:
    default: true
    description: "Normal permission"
   factionui.use.admin:
    default: op
    description: "Admin permission"